export const bio = {
  name: 'Sammii Kellow',
  title: 'Full-Stack Developer & Creative Technologist',
  location: 'United Kingdom',
  web: 'sammii.dev',
  github: 'github.com/sammii-hk',
  x: '@sammiihk',
  linkedin: 'linkedin.com/in/sammii',
};

export const about = `Full-stack developer with a background in creative technology and a habit of shipping. I've built and deployed 30+ projects spanning real-time data visualisation, AI pipelines, WebGL shaders, autonomous agent systems, and self-hosted infrastructure. My core stack is Next.js, TypeScript, and PostgreSQL, but I'll pick up whatever the problem needs. I care about craft, performance, and building things that actually work.`;

export const products = [
  {
    name: 'Gamut',
    tech: 'Next.js, TypeScript, OKLCH, Tailwind CSS',
    desc: 'Real-time theme builder with OKLCH colour science, 11-step palette generation, gamut clamping, and WCAG contrast checking',
    url: 'gamut-1wsnkygq0-sammiis-projects.vercel.app',
    github: 'github.com/Sammii-HK/gamut',
  },
  {
    name: 'Kern',
    tech: 'Next.js, Tailwind CSS, Framer Motion, TypeScript',
    desc: 'Interactive typography explorer for variable fonts, optical sizing, and fluid type scales',
    url: 'kern-9u5vawme5-sammiis-projects.vercel.app',
    github: 'github.com/Sammii-HK/kern',
  },
  {
    name: 'Prism',
    tech: 'Next.js, Framer Motion, GLSL, TypeScript',
    desc: 'Design engineering component library with autonomous daily builds and shader experiments',
    url: 'prism-9r1bu6mmn-sammiis-projects.vercel.app',
    github: 'github.com/Sammii-HK/prism',
  },
  {
    name: 'ScapeStudio',
    tech: 'Next.js, TypeScript, Web Workers, Canvas 2D, Zustand',
    desc: 'Browser-based photo editor for fine art prints with grayscale pipeline and batch 300 DPI export',
    url: 'scapestudio.vercel.app',
    github: 'github.com/Sammii-HK/scapestudio',
  },
  {
    name: 'Lattiq',
    tech: 'Next.js, Lexical, Yjs, WebSockets, TypeScript',
    desc: 'Local-first collaborative rich text editor with Yjs CRDTs and real-time sync',
    url: 'lattiq-ed0hcekw6-sammiis-projects.vercel.app',
    github: 'github.com/Sammii-HK/lattiq',
  },
  {
    name: 'Lunary',
    tech: 'Next.js, TypeScript, Astronomy Engine',
    desc: 'Astrology PWA with real-time planetary positions, 500+ grimoire pages, and push notifications',
    url: 'lunary.app',
    github: 'github.com/Sammii-HK/lunary',
  },
  {
    name: 'Spellcast',
    tech: 'Next.js, Turborepo, Drizzle, PostgreSQL, Docker',
    desc: 'Self-hosted social media scheduling across 8+ platforms with 100+ MCP tools',
    url: 'spellcast.sammii.dev',
    github: 'github.com/Sammii-HK/spellcast',
  },
  {
    name: 'Orbit',
    tech: 'Node.js, Claude Code SDK, Windmill',
    desc: 'Autonomous content command centre with 14 AI agents across a multi-stage pipeline',
    github: 'github.com/Sammii-HK/orbit',
  },
  {
    name: 'Podify',
    tech: 'Next.js, Kokoro TTS, ffmpeg',
    desc: 'AI podcast generator — any text to a two-host episode for ~$0.04',
    url: 'podify-topaz.vercel.app',
    github: 'github.com/Sammii-HK/podify',
  },
  {
    name: 'Conjure',
    tech: 'Next.js, Turborepo, Groq, Chrome Extension MV3',
    desc: 'AI prompt builder for Midjourney, FLUX, and DALL-E with Chrome extension',
    url: 'conjure-two.vercel.app',
    github: 'github.com/Sammii-HK/conjure',
  },
  {
    name: 'iPrep',
    tech: 'Next.js, OpenAI Whisper, GPT-4, Prisma, Web Audio API',
    desc: 'AI-powered spoken interview practice with transcription and multi-dimensional scoring',
    url: 'iprep-five.vercel.app',
    github: 'github.com/Sammii-HK/iprep',
  },
  {
    name: 'Artify',
    tech: 'Next.js, Remotion, FLUX, Kling',
    desc: 'Automated daily content pipeline for astrology illustrations, carousels, and reels',
    url: 'artify-roan.vercel.app',
    github: 'github.com/Sammii-HK/artify',
  },
  {
    name: 'Flip',
    tech: 'Next.js, Prisma, PostgreSQL, TypeScript, Zod',
    desc: 'Feature flag and A/B testing service with MurmurHash3 and statistical significance engine',
    github: 'github.com/Sammii-HK/flip',
  },
  {
    name: 'init-mcp-server',
    tech: 'Node.js, TypeScript, tsup, Prompts',
    desc: 'CLI scaffolder for MCP servers — interactive prompts, example tools, ready to use',
    url: 'npmjs.com/package/init-mcp-server',
    github: 'github.com/Sammii-HK/create-mcp-server',
  },
  {
    name: 'Pizzazz',
    tech: 'JavaScript, Rollup, npm',
    desc: 'Published npm package — customisable click/hover effects, ~1KB, zero dependencies',
    url: 'npmjs.com/package/@unicorn-poo/pizzazz',
    github: 'github.com/Sammii-HK/pizzazz',
  },
  {
    name: 'sammii-cli',
    tech: 'Node.js, Ink, React, chalk',
    desc: 'This terminal portfolio — run npx sammii from anywhere',
    url: 'npmjs.com/package/sammii',
    github: 'github.com/Sammii-HK/sammii-cli',
  },
  {
    name: 'Glint',
    tech: 'Next.js, Edge Middleware, PostgreSQL',
    desc: 'Custom analytics platform with zero-latency tracking via Edge Middleware',
    url: 'glint-dun.vercel.app',
    github: 'github.com/Sammii-HK/glint',
  },
  {
    name: 'Crystal Index',
    tech: 'Next.js, Prisma, GPT-4, React Three Fiber',
    desc: 'Crystal catalogue CMS with AI-generated descriptions and 3D rendering',
    url: 'crystalindex.co.uk',
    github: 'github.com/Sammii-HK/crystal-index',
  },
  {
    name: 'The CSS Color Game',
    tech: 'Next.js, Edge Middleware, React Email, Resend',
    desc: 'Daily colour recognition game with automated email delivery',
    url: 'thecolorgame.uk',
    github: 'github.com/Sammii-HK/the-colour-game',
  },
  {
    name: 'Succulent',
    tech: 'Next.js, Ayrshare, AI SDK, Stripe, Shopify',
    desc: 'Social media management with print-on-demand and e-commerce automation',
    url: 'succulent.sammii.dev',
    github: 'github.com/Sammii-HK/unicorn-poo',
  },
  {
    name: 'Scape²',
    tech: 'Next.js, Vercel E-commerce, Shopify',
    desc: 'E-commerce storefront integrated with Shopify APIs',
    url: 'scsq.uk',
    github: 'github.com/Sammii-HK/scape-squared',
  },
];

export const experiments = [
  {
    name: 'Kinetic',
    tech: 'Next.js, Framer Motion, TypeScript',
    desc: '25 interactive demos: spring physics, gestures, SVG morphing, scroll parallax',
    url: 'kinetic-f1boklnik-sammiis-projects.vercel.app',
    github: 'github.com/Sammii-HK/kinetic',
  },
  {
    name: 'Spectra',
    tech: 'Three.js, GLSL, Web Audio API',
    desc: 'Audio-reactive shader visualiser driven by microphone input',
    url: 'spectra.sammii.dev',
    github: 'github.com/Sammii-HK/spectra',
  },
  {
    name: 'Refract',
    tech: 'WebGL, GLSL',
    desc: 'Text-to-shader generative art tool — type a word, get a unique shader',
    url: 'refract-8mv500w8w-sammiis-projects.vercel.app',
    github: 'github.com/Sammii-HK/refract',
  },
  {
    name: 'Grove',
    tech: 'Next.js, Canvas API, Sprite Engine',
    desc: 'Pixel-art forest sim with time-of-day lighting, seasons, and fireflies',
    url: 'grove-bnzmufpnf-sammiis-projects.vercel.app',
    github: 'github.com/Sammii-HK/grove',
  },
  {
    name: 'Isle',
    tech: 'TypeScript, Canvas, VS Code Extension',
    desc: 'VS Code extension — Claude Code agents as pixel-art villagers',
    github: 'github.com/Sammii-HK/isle',
  },
  {
    name: 'Beyond Light VR',
    tech: 'Three.js, WebXR, GLSL',
    desc: 'WebXR reconstruction of my MA dissertation installation',
    url: 'beyond-light-vr.vercel.app',
    github: 'github.com/Sammii-HK/beyond-light-vr',
  },
  {
    name: 'Celestial Map',
    tech: 'D3.js, Canvas',
    desc: 'Interactive star globe with constellation lines and magnitude-scaled stars',
    github: 'github.com/Sammii-HK/celestial-map',
  },
  {
    name: 'Creative Coding',
    tech: 'p5.js',
    desc: '15 visual experiments treating a photograph as raw material',
    url: 'creative-coding-csu90bcmk-sammiis-projects.vercel.app',
    github: 'github.com/Sammii-HK/creative-coding',
  },
  {
    name: 'Tailwind Colour Creator',
    tech: 'React, TypeScript, Vite, Tailwind CSS',
    desc: 'Tailwind-accurate 11-step colour palette generator from any base colour',
    url: 'tailwind-colour-creator.vercel.app',
    github: 'github.com/Sammii-HK/tailwind-colour-creator',
  },
  {
    name: 'Liquidity',
    tech: 'Next.js, GSAP, Rapier2D',
    desc: 'Liquid text effects with physics simulation',
    url: 'liquidity-ten.vercel.app',
    github: 'github.com/Sammii-HK/liquidity',
  },
  {
    name: 'Day Lite',
    tech: 'React, Mapbox GL',
    desc: 'Interactive globe visualising daylight patterns worldwide',
    url: 'day-lite.vercel.app',
    github: 'github.com/Sammii-HK/day-lite',
  },
  {
    name: 'Balloon Bonanza',
    tech: 'React, Matter.js',
    desc: 'Physics simulation with interactive balloons and collision dynamics',
    url: 'balloon-bonanza.vercel.app',
    github: 'github.com/Sammii-HK/balloon-bonanza',
  },
  {
    name: 'Rainbow Laser Pointer',
    tech: 'React, TypeScript, Canvas',
    desc: 'Interactive laser pointer with smooth trail rendering and colour transitions',
    url: 'rainbow-laser-pointer.vercel.app',
    github: 'github.com/Sammii-HK/rainbow-laser-pointer',
  },
  {
    name: 'Volcano Visualisation',
    tech: 'D3.js, React Three Fiber',
    desc: '3D globe mapping volcanic eruptions worldwide using GeoJSON',
    url: 'volcano-visualisation.vercel.app',
    github: 'github.com/Sammii-HK/volcanoVisualisation',
  },
  {
    name: 'Artistry',
    tech: 'React, Python, SQL',
    desc: 'Rijksmuseum API browser with SQL persistence via Python REST API',
    url: 'artistry-hq2r.onrender.com',
    github: 'github.com/Sammii-HK/artistry',
  },
  {
    name: 'Communication Infographic',
    tech: 'React',
    desc: 'Interactive timeline of communication technology milestones',
    url: 'communication-infographic.vercel.app',
    github: 'github.com/Sammii-HK/communication-infographic',
  },
];
